FROM arm64v8/alpine as gobuild
RUN apk update && apk add build-base pkgconfig go git libzmq zeromq-dev alpine-sdk libsodium-dev

ENV GOPATH /
WORKDIR /

#COPY . . if you update the libs below build with --no-cache
RUN go get -d github.com/gorilla/mux
RUN go get -d github.com/me-box/lib-go-databox
RUN go get -d github.com/sausheong/hs1xxplug
COPY . .
RUN addgroup -S databox && adduser -S -g databox databox
RUN GGO_ENABLED=0 GOOS=linux go build -a -tags netgo -installsuffix netgo -ldflags '-s -w' -o app /src/*.go

FROM arm64v8/alpine:3.8
COPY --from=gobuild /etc/passwd /etc/passwd
RUN apk update && apk add libzmq
USER databox
WORKDIR /
COPY --from=gobuild /app .
COPY --from=gobuild /www/ /www/
COPY --from=gobuild /tmpl/ /tmpl/
LABEL databox.type="driver"
EXPOSE 8080

CMD ["./app"]
#CMD ["sleep","2147483647"]
